plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
rootProject.name = 'RandomItem'
def loader = providers.gradleProperty('loader').getOrElse('forge')
if (!(loader in ['forge', 'neoforge'])) throw new GradleException("Unsupported loader: ${loader}")
if (loader == 'neoforge') rootProject.buildFileName = 'build-neoforge.gradle'
