modLoader="javafml"
loaderVersion="[${forge_major},)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/mel1x/RandomItem/issues"
[[mods]]
modId="randomitem"
version="${mod_version}"
displayName="Random Items Command"
displayURL="https://modrinth.com/mod/random-items-cmd"
authors="Mel1x"
displayTest="IGNORE_SERVER_VERSION"
description='''Adds /getRandomItem [count] [maxStack] to give random vanilla and modded items.'''
[[dependencies.randomitem]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.randomitem]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
